#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Laurie's Digital Garden

# Short bio or description (displayed in the header)
description: Curate and grow.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:%3Csvg viewBox='0 0 36 36' fill='none' xmlns='http://www.w3.org/2000/svg' width='80' height='80' colors='%23260729,%232a2344,%23495168,%23ccbd9e,%23d8ccb2' name='Coretta Scott' size='80'%3E%3Cmask id='mask__beam' maskUnits='userSpaceOnUse' x='0' y='0' width='36' height='36'%3E%3Crect width='36' height='36' rx='20' fill='white'%3E%3C/rect%3E%3C/mask%3E%3Cg mask='url(%23mask__beam)' fill='transparent'%3E%3Crect width='36' height='36' rx='20' fill='%23495168'%3E%3C/rect%3E%3Crect x='0' y='0' width='36' height='36' transform='translate(9 -5) rotate(199 18 18) scale(1.1)' fill='%23d8ccb2' rx='6'%3E%3C/rect%3E%3Cg transform='translate(4.5 -5) rotate(9 18 18)'%3E%3Cpath d='M15 20c2 1 4 1 6 0' stroke='black' fill='none' stroke-linecap='round'%3E%3C/path%3E%3Crect x='10' y='14' width='1.5' height='2' rx='1' stroke='none' fill='black'%3E%3C/rect%3E%3Crect x='24' y='14' width='1.5' height='2' rx='1' stroke='none' fill='black'%3E%3C/rect%3E%3C/g%3E%3C/g%3E%3C/svg%3E

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:  
  instagram:
  linkedin:
  pinterest:
  rss: laurieqiu-rss
  twitter:  
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
